//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Матбои.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Матбои.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.Windows;
        ///
        ///// Общие сведения об этой сборке предоставляются следующим набором
        ///// набор атрибутов. Измените значения этих атрибутов, чтобы изменить сведения,
        ///// связанные со сборкой.
        ///[assembly: AssemblyTitle(&quot;Матбои&quot;)]
        ///[assembly: AssemblyDescription(&quot;Ведение протокола Матбоя&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;&quot;)]
        ///[assembly: AssemblyProduct(&quot;Матбои&quot;)]
        ///[assembly: AssemblyCopyright(&quot;Copyright [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string AssemblyInfo {
            get {
                return ResourceManager.GetString("AssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     Этот код создан программой.
        /////     Исполняемая версия:4.0.30319.42000
        /////
        /////     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
        /////     повторной генерации кода.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace Матбои.Properties {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   К [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Resources_Designer {
            get {
                return ResourceManager.GetString("Resources_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;SettingsFile xmlns=&quot;uri:settings&quot; CurrentProfile=&quot;(Default)&quot;&gt;
        ///  &lt;Profiles&gt;
        ///    &lt;Profile Name=&quot;(Default)&quot; /&gt;
        ///  &lt;/Profiles&gt;
        ///  &lt;Settings /&gt;
        ///&lt;/SettingsFile&gt;.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace Матбои.Properties
        ///{
        ///
        ///
        ///    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Settings_Designer {
            get {
                return ResourceManager.GetString("Settings_Designer", resourceCulture);
            }
        }
    }
}
